### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by TeslaLyon** [usamamuneerchaudhary/commentify#1]
log info :

 Problem 1
    - Root composer.json requires usamamuneerchaudhary/commentify ^1.0 -> satisfiable by usamamuneerchaudhary/commentify[1.0].
    - usamamuneerchaudhary/commentify 1.0 requires illuminate/database >=v10.1.4 -> found illuminate/database[dev-master, v10.1.4, ..., 10.x-dev, 11.x-dev (alias of dev-master)] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require usamamuneerchaudhary/commentify:*" to figure out if any version is installable, or "composer require usamamuneerchaudhary/commentify:^2.1" if you know which you need.

problem : 
Do I also need to install the illuminate/database package?

**Comment by usamamuneerchaudhary** [comment]
This should be fixed now with new release! Thanks for highlighting this one !
