### ISSUE TITLE
Uncaught ReferenceError: detectAtSymbol is not defined     at HTMLTextAreaElement.oninput

### ISSUE THREAD

**Issue by Vladika-sys** [usamamuneerchaudhary/commentify#15]
Hello. I did everything exactly as in the description, but when I enter text, I get the error Uncaught ReferenceError: detectAtSymbol is not defined at HTMLTextAreaElement.oninput (18042023?_token=dUaEICCsSudBH0gvbhUyYUedirEjlgXg5kndG9OO:220:10). When the button is pressed, the page restarts, and the comment is not added

**Comment by 4lpcuong** [comment]
how can you fix it, i facing it today ...
