### ISSUE TITLE
problem with the commentify display

### ISSUE THREAD

**Issue by FaizHebat347** [usamamuneerchaudhary/commentify#16]
hello sir, I want to ask about your commentify project, I have used yours but why does it look messy? Below I will put the display. Thank you, sorry to disturb you ;)

**Comment by usamamuneerchaudhary** [comment]
> hello sir, I want to ask about your commentify project, I have used yours but why does it look messy? Below I will put the display. Thank you, sorry to disturb you ;)

Hey, could you please share screenshot, how is it looking messy please? So I could have a better understanding of the issue you're facing

**Comment by FaizHebat347** [comment]
[image: komen1.PNG][image: komen2.PNG]
Hi sir, here is a screenshot of the messy comments, thank you, sorry to
bother you ;)

Pada Rab, 28 Feb 2024 pukul 13.22 Usama Muneer ***@***.***>
menulis:

**Comment by usamamuneerchaudhary** [comment]
Can't see any attachment, could you please upload again? 
<img width="733" alt="Screenshot 2024-03-02 at 16 18 17" src="https://github.com/usamamuneerchaudhary/commentify/assets/24513380/ddd67495-6a65-4c95-a3ec-666e0281b892">

**Comment by Prastyo-EL** [comment]
![Screen Shot 2024-03-04 at 23 52 27](https://github.com/usamamuneerchaudhary/commentify/assets/52477300/712324d0-12a4-4fee-b506-efea2dc0c441)
reply comment not showing

**Comment by usamamuneerchaudhary** [comment]
Please make sure that styles are properly built.
Also, there's a config you can set to enable/disable comment nesting.
`comment_nesting` => `true` will show reply block.
