### ISSUE TITLE
detectAtSymbol needs fixing

### ISSUE THREAD

**Issue by PovilasKorop** [usamamuneerchaudhary/commentify#2]
Not sure if it directly affects the behavior, but I see console errors for `detectAtSymbol` method.

Two different errors:

<img width="1509" alt="Screenshot 2023-04-23 at 10 24 35" src="https://user-images.githubusercontent.com/1510147/233826038-35adb698-0001-4d8f-8ea2-78ef8b63409f.png">
<img width="1603" alt="Screenshot 2023-04-23 at 10 25 33" src="https://user-images.githubusercontent.com/1510147/233826040-f041f533-7f47-4d56-8301-d763029d0083.png">

If there are no comments, then this method is never loaded.
If there is a comment, then there's something with `selectionStart`

**Comment by usamamuneerchaudhary** [comment]
@PovilasKorop Thanks for pointing this out. As a temporary fix, just added a condition and throws a console warning if element not found.
