### ISSUE TITLE
livewire foreach need key. 

### ISSUE THREAD

**Issue by magic-thomas** [usamamuneerchaudhary/commentify#3]
Thanks for good package. This is what I was looking for for long time. 

And It is just teasing. 

in `resources/views/livewire/partials/dropdowns/users.blade.php` 

` <li wire:click="selectUser('{{ $user->name }}')">`

With my experiences, it would be better to put `:key` 

` <li wire:click="selectUser('{{ $user->name }}')" wire:key='{{ $user->id() }}'>`

**Comment by usamamuneerchaudhary** [comment]
@magic-thomas glad that you liked the package, hope you enjoy using it too.

Good catch, I've added that in the new release :)
