### ISSUE TITLE
Add Livewire v3 Support 

### ISSUE THREAD

**Issue by zeusmartinsoly** [usamamuneerchaudhary/commentify#5]
Can you develop this package to support Livewire v3?

**Comment by usamamuneerchaudhary** [comment]
@zeusmartinsoly , thanks for the comment, actually waiting for the stable release, will update then :)

**Comment by Nathan269** [comment]
Nice package, planning to implement this within the next project when it is compatible with Livewire v3. Any update on this?

**Comment by zeusmartinsoly** [comment]
Thank you @usamamuneerchaudhary 
Any update on this?

**Comment by usamamuneerchaudhary** [comment]
Added support for Livewire v3, please update the package. Thanks :) 

Closing now.
