### ISSUE TITLE
how to publish the views so ican changfe them

### ISSUE THREAD

**Issue by BenOussama180** [usamamuneerchaudhary/commentify#8]

**Comment by vasilejianu** [comment]
Need info on this too please 
Thank you

**Comment by vasilejianu** [comment]
ok so you need to copy this folder from

/vendor/usamamuneerchaudhary/commentify/resources/views/livewire

to

/resources/vendor/commentify/livewire

then you can customize your blade files as you want

**Comment by Uhasith** [comment]
I'm using this package with Filament PHP. But my tailwind css classes not working. Any idea with that? 

@vasilejianu

**Comment by Uhasith** [comment]
I copied the folder  to this path `/resources/vendor/commentify/livewire`. But when i inspect the button element it's getting css classes from `/vendor/usamamuneerchaudhary/commentify/resources/views/livewire` these files. Any idea why?

@vasilejianu

**Comment by Uhasith** [comment]
@usamamuneerchaudhary How can i publish views without manually copying the Folders and files?

**Comment by As3ad10** [comment]
@Uhasith  Did you run `npm run dev` or `npm run build`

**Comment by kolydart** [comment]
> I copied the folder to this path `/resources/vendor/commentify/livewire`. But when i inspect the button element it's getting css classes from these files `/vendor/usamamuneerchaudhary/commentify/resources/views/livewire` . Any idea why?
> @vasilejianu

In my case, I had to copy it to `/resources/views/vendor/commentify/livewire`, instead of `/resources/vendor/commentify/livewire`

**Comment by usamamuneerchaudhary** [comment]
You can run `php artisan vendor:publish --tag=commentify-views` to publish views :) hope this helps.
