### ISSUE TITLE
Attempt to read property "user" on null on replies

### ISSUE THREAD

**Issue by vasilejianu** [usamamuneerchaudhary/commentify#9]
<p class="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white"><img

                            class="mr-2 w-6 h-6 rounded-full"

                            src="{{$comment->user->avatar()}}"

                            alt="{{$comment->user->name}}">{{Str::ucfirst($comment->user->name)}}</p>

                    <p class="text-sm text-gray-600 dark:text-gray-400">

                        <time pubdate datetime="{{$comment->presenter()->relativeCreatedAt()}}"

                              title="{{$comment->presenter()->relativeCreatedAt()}}">

                            {{$comment->presenter()->relativeCreatedAt()}}

                        </time>

this throws the following ex Attempt to read property "user" on null on replies 
i've @dd($comment->user->name) its its coming back with the value so have no idea whats happening here

**Comment by Uhasith** [comment]
Having same issue when try to view replies 🙂

**Comment by vasilejianu** [comment]
ok so you need to copy this folder from

/vendor/usamamuneerchaudhary/commentify/resources/views/livewire 

to

/resources/vendor/commentify/livewire

and edit comment.blade.php 

find  <livewire:comment :$child :key="$child->id"/> and change it to 

<livewire:comment :comment="$child" :key="$child->id"/>

**Comment by usamamuneerchaudhary** [comment]
should be fixed with the new release, thanks for flagging :)

**Comment by Uhasith** [comment]
So how can i change Tailwind css classes? I change colors of the button. But not applied? 
@usamamuneerchaudhary @vasilejianu 
<img width="938" alt="Screenshot 2023-09-15 at 09 05 46" src="https://github.com/usamamuneerchaudhary/commentify/assets/78094049/f737227c-3359-40fd-8915-3a7da544591a">
